version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: db
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
     - ../.env

volumes:
  postgres_data:
